version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - run:
          name: Base64を使用して複数行の環境変数を扱う
          environment:
            MULTILINE_ENV_VAR: MeihjOebrgoy6KGM55uuCg==
          command: |
            echo $MULTILINE_ENV_VAR | base64 --decode